version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=975519379312.dkr.ecr.us-east-2.amazonaws.com/ogbrown-courses-rest
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo First seven of Commit Hash is $COMMIT_HASH
      - IMAGE_TAG=$COMMIT_HASH
      - echo Image tag is $IMAGE_TAG
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - docker info
      - echo Building the Docker image...
      - echo docker build -t $REPOSITORY_URI:latest .
      - docker build -t $REPOSITORY_URI:latest .
      - echo docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
      - echo docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"ogb-courses-rest-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json